name: Verify Pull Request
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
jobs:
  lint-and-test:
    name: Lint and Test
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 17.5.0
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
